web/router.ex
defmodule Db8.Router do
  use Db8.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug DB8.Auth, repo: DB8.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Db8 do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController
    resources "/schools", SchoolController
    get "/debate_role", DebateRoleController, :index
    resources "/teams", TeamController
    resources "/tournaments", TournamentController
    resources "/tournament_judges", TournamentJudgeController
    resources "/tournament_coaches", TournamentCoachController
    resources "/tournament_teams", TournamentTeamController
    resources "/debates", DebateController
    resources "/debate_scores", DebateScoreController
    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  # Other scopes may use custom stacks.
  # scope "/api", Db8 do
  #   pipe_through :api
  # end
end

lib/db8/endpoint.ex
defmodule Db8.Endpoint do
  use Phoenix.Endpoint, otp_app: :db8

  socket "/socket", Db8.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :db8, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  plug Plug.Session,
    store: :cookie,
    key: "_db8_key",
    signing_salt: "2MJSUcTJ"

  plug Db8.Router
end

lib/db8/repo.ex
defmodule Db8.Repo do
  use Ecto.Repo, otp_app: :db8

end

web/models/debate.ex
defmodule Db8.Debate do
  use Db8.Web, :model

  schema "debate" do
    field :propteam, :integer
    field :oppteam, :integer
    field :propscore, :integer
    field :oppscore, :integer
    field :tournamentid, :integer
    field :motion, :string

  end

  @required_fields ~w(tournamentid propteam oppteam motion)
  @optional_fields ~w()

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end
end

web/models/debate_role.ex
defmodule Db8.DebateRole do
  use Db8.Web, :model

  schema "debate_role" do
    field :role, :string
  end

  @required_fields ~w(role)
  @optional_fields ~w()

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end
end

web/models/debate_score.ex
defmodule Db8.DebateScore do
  use Db8.Web, :model

  schema "debate_score" do
    field :debater, :integer
    field :debaterole, :integer
    field :debate, :integer
    field :content, :integer
    field :strategy, :integer
    field :style, :integer

  end

  @required_fields ~w(debater debateRole debate content strategy style)
  @optional_fields ~w()

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end
end

web/models/school.ex
defmodule Db8.School do
  use Db8.Web, :model

  schema "school" do
    field :name, :string
    field :address, :string
    field :phone, :string
  end

  @required_fields ~w(name address phone)
  @optional_fields ~w()

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end
end

web/models/team.ex
defmodule Db8.Team do
  use Db8.Web, :model

  schema "team" do
    field :name, :string
    field :affiliationschoolid, :integer
    field :firstmember, :integer
    field :secondmember, :integer
    field :thirdmember, :integer

  end

  @required_fields ~w(name affiliationschoolid firstmember secondmember thirdmember)
  @optional_fields ~w()

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end
end

web/models/tournament.ex
defmodule Db8.Tournament do
  use Db8.Web, :model

  schema "tournament" do
    field :name, :string
    field :host, :integer
    field :admin, :integer
  end

  @required_fields ~w(name host admin)
  @optional_fields ~w()

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end
end

web/models/tournament_coach.ex
defmodule Db8.TournamentCoach do
  use Db8.Web, :model

  schema "tournament_coaches" do
    field :tournamentid, :integer
    field :affiliationschoolid, :integer
    field :userid, :integer

  end

  @required_fields ~w(tournamentid affiliaffiliationschoolid userid)
  @optional_fields ~w()

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end
end

web/models/tournament_team.ex
defmodule Db8.TournamentTeam do
  use Db8.Web, :model

  schema "tournament_teams" do
    field :tournamentid, :integer
    field :affiliationschoolid, :integer
    field :teamid, :integer

  end

  @required_fields ~w(tournamentid affiliaffiliationschoolid teamid)
  @optional_fields ~w()

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end
end

web/models/users.ex
defmodule Db8.User do
  use Db8.Web, :model

  schema "users" do
    field :name, :string
    field :username, :string
    field :password, :string, virtual: true
    field :password_hash, :string

    timestamps
  end

  def changeset(model, params \\ :empty) do
    model
    |> cast(params, ~w(name username), [])
    |> validate_length(:username, min: 1, max: 20)
  end

  def registration_changeset(model, params \\ :empty) do
    model
    |> changeset(params)
    |> cast(params, ~w(password), [])
    |> validate_length(:password, min: 6, max: 100)
    |> put_pass_hash()
  end

  def put_pass_hash(changeset) do
    case changeset do
      %Ecto.Changeset{valid?: true, changes: %{password: pass}} ->
        put_change(changeset, :password_hash, Comeonin.Bcrypt.hashpwsalt(pass))
        _ ->
          changeset
    end
  end
end

web/views/debate_role_view.ex
defmodule Db8.DebateRoleView do
  use Db8.Web, :view
end

web/views/debate_view.ex
defmodule Db8.DebateView do
  use Db8.Web, :view
end

web/views/error_view.ex
defmodule Db8.ErrorView do
  use Db8.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Server internal error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule Db8.LayoutView do
  use Db8.Web, :view
end

web/views/page_view.ex
defmodule Db8.PageView do
  use Db8.Web, :view
end

web/views/school_view.ex
defmodule Db8.SchoolView do
  use Db8.Web, :view
end

web/views/session_view.ex
defmodule DB8.SessionView do
  use Db8.Web, :view
end

web/views/team_view.ex
defmodule Db8.TeamView do
  use Db8.Web, :view
end

web/views/tournament_view.ex
defmodule Db8.TournamentView do
  use Db8.Web, :view
end

web/views/user_view.ex
defmodule Db8.UserView do
  use Db8.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>DB8!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link href='http://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  </head>

  <body class = "Syte">
    <nav>
      <div class="col-xs-6">
        <a href="<%= page_path @conn, :index %>">
          <div class="logo">
            <br /><br>
            DBTrs
          </div>
        </a>

      </div>

      <div class="col-xs-6 text-right">
        <div id="header-links">
          <%= if @current_user do %>
            <li><%= @current_user.username %></li>
            <li>
              <%= link "Log out", to: session_path(@conn, :delete, @current_user), method: "delete" %>
            </li>
           <% else %>
            <li><%= link "Register", to: user_path(@conn, :new) %></li>
            <li><%= link "Tournaments", to: tournament_path(@conn, :index) %></li>
          <% end %>
        </div>
      </div>
    </nav>


    <main class="Site-content">
    <%= @inner %>
    </main>
<!--
    <footer>
      <div class="col-xs-6">
        LEFT SIDE
      </div>
      <div class="col-xs-6">
        RIGHT SIDE
      </div>
    </footer>
  </body>-->
  <!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="../../dist/js/bootstrap.min.js"></script>
<link href="http://amcharts.com/lib/3/plugins/export/export.css" rel="stylesheet" type="text/css">
<!-- Just to make our placeholder images work. Don't actually copy the next line! -->
<script src="../../assets/js/vendor/holder.min.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
<script src="http://www.amcharts.com/lib/3/amcharts.js"></script>
<script src="http://www.amcharts.com/lib/3/serial.js"></script>
<script src="http://www.amcharts.com/lib/3/themes/light.js"></script>
<script src="amcharts/exporting/amexport.js" type="text/javascript"></script>
<script src="amcharts/exporting/canvg.js" type="text/javascript"></script>
<script src="amcharts/exporting/rgbcolor.js" type="text/javascript"></script>
<script src="amcharts/exporting/filesaver.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/amcharts/3.13.0/exporting/canvg.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/amcharts/3.13.0/exporting/rgbcolor.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/amcharts/3.13.0/exporting/filesaver.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/amcharts/3.13.0/exporting/amexport.js" type="text/javascript"></script>
<script src="http://amcharts.com/lib/3/plugins/export/export.js" type="text/javascript"></script>


</script>
<script type="text/javascript">
var chart = AmCharts.makeChart("chartdiv", {
    "type": "serial",
    "theme": "light",
    "marginRight": 80,
    "autoMarginOffset": 20,
    "dataDateFormat": "YYYY-MM-DD",
    "valueAxes": [{
        "id": "v1",
        "axisAlpha": 0,
        "position": "left"
    }],
    "balloon": {
        "borderThickness": 1,
        "shadowAlpha": 0
    },
    "graphs": [{
        "id": "g1",
        "bullet": "round",
        "bulletBorderAlpha": 1,
        "bulletColor": "#FFFFFF",
        "bulletSize": 5,
        "hideBulletsCount": 50,
        "lineThickness": 2,
        "title": "red line",
        "useLineColorForBulletBorder": true,
        "valueField": "value",
        "balloonText": "<div style='margin:5px; font-size:19px;'><span style='font-size:13px;'>[[category]]</span><br>[[value]]</div>"
    }],
    "chartScrollbar": {
        "graph": "g1",
        "oppositeAxis":false,
        "offset":30,
        "scrollbarHeight": 80,
        "backgroundAlpha": 0,
        "selectedBackgroundAlpha": 0.1,
        "selectedBackgroundColor": "#888888",
        "graphFillAlpha": 0,
        "graphLineAlpha": 0.5,
        "selectedGraphFillAlpha": 0,
        "selectedGraphLineAlpha": 1,
        "autoGridCount":true,
        "color":"#AAAAAA"
    },
    "chartCursor": {
        "pan": true,
        "valueLineEnabled": true,
        "valueLineBalloonEnabled": true,
        "cursorAlpha":0,
        "valueLineAlpha":0.2
    },
    "categoryField": "date",
    "categoryAxis": {
        "parseDates": true,
        "dashLength": 1,
        "minorGridEnabled": true
    },
    "export": {
        "enabled": true
    },
  "dataProvider": [{
      "date": "2015-07-27",
      "value": 13
  }, {
      "date": "2015-07-28",
      "value": 11
  }, {
      "date": "2015-07-29",
      "value": 15
  }, {
      "date": "2015-07-30",
      "value": 16
  }, {
      "date": "2015-07-31",
      "value": 18
  }, {
      "date": "2015-08-01",
      "value": 13
  }, {
      "date": "2015-08-02",
      "value": 22
  }, {
      "date": "2015-08-03",
      "value": 23
  }, {
      "date": "2015-08-04",
      "value": 20
  }, {
      "date": "2015-08-05",
      "value": 17
  }, {
      "date": "2015-08-06",
      "value": 16
  }, {
      "date": "2015-08-07",
      "value": 18
  }, {
      "date": "2015-08-08",
      "value": 21
  }, {
      "date": "2015-08-09",
      "value": 26
  }, {
      "date": "2015-08-10",
      "value": 24
  }, {
      "date": "2015-08-11",
      "value": 29
  }, {
      "date": "2015-08-12",
      "value": 32
  }, {
      "date": "2015-08-13",
      "value": 18
  }, {
      "date": "2015-08-14",
      "value": 24
  }, {
      "date": "2015-08-15",
      "value": 22
  }, {
      "date": "2015-08-16",
      "value": 18
  }, {
      "date": "2015-08-17",
      "value": 19
  }, {
      "date": "2015-08-18",
      "value": 14
  }, {
      "date": "2015-08-19",
      "value": 15
  }, {
      "date": "2015-08-20",
      "value": 12
  }, {
      "date": "2015-08-21",
      "value": 8
  }, {
      "date": "2015-08-22",
      "value": 9
  }, {
      "date": "2015-08-23",
      "value": 8
  }, {
      "date": "2015-08-24",
      "value": 7
  }, {
      "date": "2015-08-25",
      "value": 5
  }, {
      "date": "2015-08-26",
      "value": 11
  }, {
      "date": "2015-08-27",
      "value": 13
  }, {
      "date": "2015-08-28",
      "value": 18
  }, {
      "date": "2015-08-29",
      "value": 20
  }, {
      "date": "2015-08-30",
      "value": 29
  }, {
      "date": "2015-08-31",
      "value": 33
  }, {
      "date": "2015-09-01",
      "value": 42
  }, {
      "date": "2015-09-02",
      "value": 35
  }, {
      "date": "2015-09-03",
      "value": 31
  }, {
      "date": "2015-09-04",
      "value": 47
  }, {
      "date": "2015-09-05",
      "value": 52
  }, {
      "date": "2015-09-06",
      "value": 46
  }, {
      "date": "2015-09-07",
      "value": 41
  }, {
      "date": "2015-09-08",
      "value": 43
  }, {
      "date": "2015-09-09",
      "value": 40
  }, {
      "date": "2015-09-10",
      "value": 39
  }, {
      "date": "2015-09-11",
      "value": 34
  }, {
      "date": "2015-09-12",
      "value": 29
  }, {
      "date": "2015-09-13",
      "value": 34
  }, {
      "date": "2015-09-14",
      "value": 37
  }, {
      "date": "2015-09-15",
      "value": 42
  }, {
      "date": "2015-09-16",
      "value": 49
  }, {
      "date": "2015-09-17",
      "value": 46
  }, {
      "date": "2015-09-18",
      "value": 47
  }, {
      "date": "2015-09-19",
      "value": 55
  }, {
      "date": "2015-09-20",
      "value": 59
  }, {
      "date": "2015-09-21",
      "value": 58
  }, {
      "date": "2015-09-22",
      "value": 57
  }, {
      "date": "2015-09-23",
      "value": 61
  }, {
      "date": "2015-09-24",
      "value": 59
  }, {
      "date": "2015-09-25",
      "value": 67
  }, {
      "date": "2015-09-26",
      "value": 65
  }, {
      "date": "2015-09-27",
      "value": 61
  }, {
      "date": "2015-09-28",
      "value": 66
  }, {
      "date": "2015-09-29",
      "value": 69
  }, {
      "date": "2015-09-30",
      "value": 55
  }, {
      "date": "2015-10-01",
      "value": 67
  }, {
      "date": "2015-10-02",
      "value": 63
  }, {
      "date": "2015-10-03",
      "value": 46
  }, {
      "date": "2015-10-04",
      "value": 32
  }, {
      "date": "2015-10-05",
      "value": 21
  }, {
      "date": "2015-10-06",
      "value": 18
  }, {
      "date": "2015-10-07",
      "value": 21
  }, {
      "date": "2015-10-08",
      "value": 28
  }, {
      "date": "2015-10-09",
      "value": 27
  }, {
      "date": "2015-10-10",
      "value": 36
  }, {
      "date": "2015-10-11",
      "value": 33
  }, {
      "date": "2015-10-12",
      "value": 31
  }, {
      "date": "2015-10-13",
      "value": 30
  }, {
      "date": "2015-10-14",
      "value": 34
  }, {
      "date": "2015-10-15",
      "value": 38
  }, {
      "date": "2015-10-16",
      "value": 37
  }, {
      "date": "2015-10-17",
      "value": 44
  }, {
      "date": "2015-10-18",
      "value": 49
  }, {
      "date": "2015-10-19",
      "value": 53
  }, {
      "date": "2015-10-20",
      "value": 57
  }, {
      "date": "2015-10-21",
      "value": 60
  }, {
      "date": "2015-10-22",
      "value": 61
  }, {
      "date": "2015-10-23",
      "value": 69
  }, {
      "date": "2015-10-24",
      "value": 67
  }, {
      "date": "2015-10-25",
      "value": 72
  }, {
      "date": "2015-10-26",
      "value": 77
  }, {
      "date": "2015-10-27",
      "value": 75
  }, {
      "date": "2015-10-28",
      "value": 70
  }, {
      "date": "2015-10-29",
      "value": 72
  }, {
      "date": "2015-10-30",
      "value": 70
  }, {
      "date": "2015-10-31",
      "value": 72
  }, {
      "date": "2015-11-01",
      "value": 73
  }, {
      "date": "2015-11-02",
      "value": 67
  }, {
      "date": "2015-11-03",
      "value": 68
  }, {
      "date": "2015-11-04",
      "value": 65
  }, {
      "date": "2015-11-05",
      "value": 55
  }, {
      "date": "2015-11-06",
      "value": 75
  }, {
      "date": "2015-11-07",
      "value": 74
  }, {
      "date": "2015-11-08",
      "value": 55
  }, {
      "date": "2015-11-09",
      "value": 76
  }, {
      "date": "2015-11-10",
      "value": 77
  }, {
      "date": "2015-11-11",
      "value": 81
  }, {
      "date": "2015-11-12",
      "value": 50
  }, {
      "date": "2015-11-13",
      "value": 55
  }, {
      "date": "2015-11-14",
      "value": 59
  }, {
      "date": "2015-11-15",
      "value": 60
  }, {
      "date": "2015-11-16",
      "value": 50
  }, {
      "date": "2015-11-17",
      "value": 40
  }, {
      "date": "2015-11-18",
      "value": 35
  }, {
      "date": "2015-11-19",
      "value": 23
  }, {
      "date": "2015-11-20",
      "value": 3
  }, {
      "date": "2015-11-21",
      "value": 1
  }, {
      "date": "2015-11-22",
      "value": 2
  }, {
      "date": "2015-11-23",
      "value": 10
  }]
});

chart.addListener("rendered", zoomChart);

zoomChart();

function zoomChart() {
  chart.zoomToIndexes(chart.dataProvider.length - 40, chart.dataProvider.length - 1);
}


</script>
</html>